webtalk_init -webtalk_dir C:/Users/meraj/az_CA_arm/az_CA_arm.sim/sim_1/behav/xsim/xsim.dir/tb_IF_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr  7 13:23:37 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "af58df15-174e-4f2e-92e3-2bb7f8ec577e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "82ac798062b2499283e6e62cbb6b3f67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "62" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1190 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "21" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "146 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "17 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "227" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "31" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "52332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3726398386 -regid "" -xml C:/Users/meraj/az_CA_arm/az_CA_arm.sim/sim_1/behav/xsim/xsim.dir/tb_IF_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/meraj/az_CA_arm/az_CA_arm.sim/sim_1/behav/xsim/xsim.dir/tb_IF_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/meraj/az_CA_arm/az_CA_arm.sim/sim_1/behav/xsim/xsim.dir/tb_IF_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
